---
- name: Configure Windows 10 Client
  hosts: windows
  tasks:
    - name: Install SNMP feature
      win_feature:
        name: SNMP
        state: present

    - name: Enable SNMP Client for Windows 10
      win_shell: |
        Add-WindowsCapability -Online -Name "SNMP.Client~~~~0.0.1.0"

    - name: Retrieve Windows Product Key
      win_shell: |
        (Get-WmiObject -query 'select * from SoftwareLicensingService').OA3xOriginalProductKey
      register: product_key

    - name: Display Windows Product Key
      debug:
        msg: "Windows Product Key: {{ product_key.stdout }}"

    - name: Add new user
      win_user:
        name: CCTV
        password: cctv
        state: present
        groups: Users
        comment: "User  account for CCTV"

    - name: Set auto login for user
      win_regedit:
        path: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: AutoAdminLogon
        type: string
        data: "1"

    - name: Set default user name for auto login
      win_regedit:
        path: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: DefaultUser Name
        type: string
        data: CCTV

    - name: Set default password for auto login
      win_regedit:
        path: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: DefaultPassword
        type: string
        data: cctv

    - name: Enable Remote Desktop
      win_regedit:
        path: HKLM\System\CurrentControlSet\Control\Terminal Server
        name: fDenyTSConnections
        type: dword
        data: 0

    - name: Allow Remote Desktop through firewall
      win_firewall_rule:
        name: "Remote Desktop"
        enable: yes
        direction: in
        action: allow
        protocol: TCP
        localport: 3389

    - name: Install Chocolatey
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; 
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; 
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install applications using Chocolatey
      win_chocolatey:
        name: "{{ item }}"
        state: present
      loop:
        - teamviewer.host
        - notepadplusplus
        - 7zip
        - googlechrome

    - name: Upgrade all Chocolatey packages
      win_chocolatey:
        name: all
        state: latest

    - name: Show current IP address
      win_shell: ipconfig
      register: ipconfig_output

    - name: Display current IP address
      debug:
        msg: "{{ ipconfig_output.stdout }}"

    - name: Final message
      debug:
        msg: "All tasks completed successfully."