---
- name: Configure Windows Host and Install Applications
  hosts: windows
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey_facts:

    - name: Install Chocolatey
      win_command: |
        @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      args:
        creates: C:\ProgramData\chocolatey

    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present

    - name: Install Notepad++
      win_chocolatey:
        name: notepadplusplus
        state: present

    - name: Install Git
      win_chocolatey:
        name: git
        state: present

    - name: Ensure Chocolatey is up to date
      win_chocolatey:
        name: chocolatey
        state: latest

    - name: Install SNMP feature using PowerShell
      win_shell: |
        Add-WindowsCapability -Online -Name "SNMP.Client~~~~0.0.1.0"
      when: ansible_os_family == "Windows"

    - name: Retrieve Windows Product Key
      win_shell: |
        (Get-WmiObject -query 'select * from SoftwareLicensingService').OA3xOriginalProductKey
      register: product_key

    - name: Display Windows Product Key
      debug:
        msg: "Windows Product Key: {{ product_key.stdout }}"
    
    - name: Create a new user
      win_user:
        name: "newuser"
        password: "P@ssw0rd"
        state: present
        description: "This is a new user account"
        groups: "Administrators"

    - name: Enable Auto Login for the new user
      win_shell: |
        Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" -Name "AutoAdminLogon" -Value "1"
        Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" -Name "DefaultUser Name" -Value "newuser"
        Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" -Name "DefaultPassword" -Value "P@ssw0rd"

    - name: Enable Remote Desktop
      win_shell: |
        Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0


    - name: Allow Remote Desktop through the firewall
      win_firewall_rule:
        name: "Remote Desktop"
        enable: yes
        direction: in
        action: allow
        localport: 3389
        protocol: TCP
    
    - name: Final message
      debug:
        msg: "All tasks completed successfully."
