---
- name: Configure Windows Host and Install Applications
  hosts: windows
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey_facts:

    - name: Install Chocolatey
      win_command: |
        @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
      args:
        creates: C:\ProgramData\chocolatey

    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present

    - name: Install Notepad++
      win_chocolatey:
        name: notepadplusplus
        state: present

    - name: Install Git
      win_chocolatey:
        name: git
        state: present

    - name: Ensure Chocolatey is up to date
      win_chocolatey:
        name: chocolatey
        state: latest

    - name: Install SNMP feature using PowerShell
      win_shell: |
        Add-WindowsCapability -Online -Name "SNMP.Client~~~~0.0.1.0"
      when: ansible_os_family == "Windows"

    - name: Retrieve Windows Product Key
      win_shell: |
        (Get-WmiObject -query 'select * from SoftwareLicensingService').OA3xOriginalProductKey
      register: product_key

    - name: Display Windows Product Key
      debug:
        msg: "Windows Product Key: {{ product_key.stdout }}"
    
    - name: Add new user
      win_user:
        name: CCTV
        password: cctv
        state: present
        groups: Users
        comment: "User  account for CCTV"

    - name: Set auto login for user
      win_regedit:
        path: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: AutoAdminLogon
        type: string
        data: "1"

    - name: Set default user name for auto login
      win_regedit:
        path: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: DefaultUser Name
        type: string
        data: CCTV

    - name: Set default password for auto login
      win_regedit:
        path: HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
        name: DefaultPassword
        type: string
        data: cctv
